// DrumEngine.h
//
// Portable, header-only PHYSICAL-MODELLING engine for an "oil drum" kit.
// No JUCE dependency: used by the VST3 wrapper and by Tools/render_demo.cpp.
//
// SOUND MODEL  (mode data: Source/ModeTables.h, recipes: Source/Voicing.h -- both GENERATED by Tools/modes.py)
//   * Each hit is a bank of 2-pole damped resonators, one per structural mode, excited by ONE shared
//     contact-force pulse (Hertz-type sin^1.5 pulse, contact time ~ v^-0.2). Every resonator rings on its
//     own after the pulse: there is no continuous noise source. Velocity therefore changes TIMBRE (shorter
//     pulse = brighter), not just level.
//   * Modes: struck lid = clamped circular plate (exact Bessel eigenvalues), side wall = Donnell shell,
//     enclosed air = closed-cylinder modes. Frequencies are ratios of the tunable fundamental ("pitch").
//   * Modal weights = plate mode shape at a randomised strike point x radiation efficiency x pair split.
//     Non-axisymmetric modes come as cos/sin PAIRS split by a fraction of a percent -> beating/shimmer.
//   * Damping: sigma(f) = sigma0 + pi*eta*f + sigma2*f^2 (loss factor), scaled per instrument.
//   * Snare wires: stochastic micro-impacts driven by shell amplitude into a 3-mode resonator bank.
//   * Cymbal family: mild memoryless nonlinearity + decaying-noise "residual" above the last modelled mode
//     (where modal overlap >> 1 and a dense mode set is statistically a noise burst).
//   * Stereo: each mode has L/R gains from its azimuthal radiation pattern; short room + soft limiter.
//
// Real-time safe: no allocation in trigger()/process(). setSampleRate() allocates (call from prepareToPlay).
#pragma once
#include <cmath>
#include <cstdint>
#include <cstring>
#include <algorithm>
#include <vector>
#include "ModeTables.h"
#include "Voicing.h"

#define OILDRUM_HAS_STEREO 1
#ifndef OILDRUM_LEGACY_GLIDE
#define OILDRUM_LEGACY_GLIDE 0      // 1 = retune ringing voices when the pitch knob moves (old behaviour)
#endif

namespace oildrum
{

constexpr float kPi = 3.14159265358979323846f;
constexpr int kMaxModes     = 256;   // per voice, after pair splitting
constexpr int kMaxInstances = 8;     // overlapping hits per instrument (rolls / flams)
constexpr int kMaxPulse     = 1024;  // samples
constexpr int kMaxResBands  = 4;
constexpr int kChunk        = 128;

enum Instrument
{
    Bass = 0, Snare1, Snare2, TomLow1, TomLow2, TomMid1, TomMid2, TomHigh1, TomHigh2,
    Splash, Ride, HihatClosed, HihatOpen, Cowbell, Rimshot
};

enum HammerType { MetalHammer = 0, WoodStick, RubberMallet };

// ---------------------------------------------------------------------------
struct Biquad          // RBJ band-pass, 0 dB peak gain
{
    float b0 = 0, b2 = 0, a1 = 0, a2 = 0, z1 = 0, z2 = 0;
    void setBandpass (float f, float q, float sr)
    {
        f = std::clamp (f, 20.0f, sr * 0.45f);
        const float w0 = 2.0f * kPi * f / sr, alpha = std::sin (w0) / (2.0f * std::max (q, 0.05f));
        const float a0 = 1.0f + alpha;
        b0 = alpha / a0; b2 = -alpha / a0; a1 = -2.0f * std::cos (w0) / a0; a2 = (1.0f - alpha) / a0;
        z1 = z2 = 0.0f;
    }
    inline float process (float x)
    { const float y = b0 * x + z1; z1 = -a1 * y + z2; z2 = b2 * x - a2 * y; return y; }
};

struct NoiseGen        // xorshift32
{
    uint32_t s = 0x9E3779B9u;
    inline float next()    { s ^= s << 13; s ^= s >> 17; s ^= s << 5; return (float) (int32_t) s * (1.0f / 2147483648.0f); }   // [-1,1)
    inline float uniform() { s ^= s << 13; s ^= s >> 17; s ^= s << 5; return (float) (s >> 8) * (1.0f / 16777216.0f); }         // [0,1)
};

inline float hash01 (uint32_t a, uint32_t b)       // deterministic per-(instrument,mode) constants
{
    uint32_t h = a * 0x9E3779B1u ^ (b + 0x7F4A7C15u) * 0x85EBCA6Bu;
    h ^= h >> 15; h *= 0x2C1B3C6Du; h ^= h >> 12; h *= 0x297A2D39u; h ^= h >> 15;
    return (float) (h >> 8) * (1.0f / 16777216.0f);
}

// ---------------------------------------------------------------------------
struct Voice
{
    bool  active = false, choking = false;
    int   nModes = 0;
    int   n = 0;                    // samples since trigger
    int   pulseLen = 0;
    float xprev = 0.0f, scrape = 0.0f;
    float pulse[kMaxPulse];
    // modal bank (structure of arrays)
    float a1[kMaxModes], a2[kMaxModes], y1[kMaxModes], y2[kMaxModes];
    float g[kMaxModes], pl[kMaxModes], pr[kMaxModes], w0[kMaxModes], gl[kMaxModes];
    // small pitch glide
    bool  glideActive = false; int glideCount = 0; float glideDelta = 0.0f, glideDecay = 1.0f;
    float hzAtTrigger = 100.0f;
    // snare wires
    bool  hasRattle = false; float rattleAmp = 0.0f, env = 0.0f, peak = 0.0f;
    float ra1[3], ra2[3], ry1[3], ry2[3];
    // cymbal nonlinearity
    float nl = 0.0f;
    // residual noise bands
    int   nRes = 0; Biquad resL[kMaxResBands], resR[kMaxResBands];
    float resAmpL[kMaxResBands], resAmpR[kMaxResBands], resDec[kMaxResBands];
    float panL = 0.7071f, panR = 0.7071f, fade = 1.0f;
};

// ---------------------------------------------------------------------------
// Short room: 6 early reflections + 4-line feedback delay network (Householder), stereo out.
class Room
{
public:
    void prepare (double sr)
    {
        erLen = (int) (0.06 * sr) + 8; erBuf.assign ((size_t) erLen, 0.0f); erPos = 0;
        static const double tl[kTaps] = { 0.0073, 0.0121, 0.0189, 0.0264, 0.0347, 0.0429 };
        static const double tr[kTaps] = { 0.0081, 0.0136, 0.0202, 0.0288, 0.0361, 0.0417 };
        static const float  gd[kTaps] = { -6.0f, -8.0f, -10.0f, -12.0f, -15.0f, -18.0f };
        for (int i = 0; i < kTaps; ++i)
        {
            dl[i] = std::max (1, (int) (tl[i] * sr)); dr[i] = std::max (1, (int) (tr[i] * sr));
            gl[i] = std::pow (10.0f, gd[i] / 20.0f); gr[i] = std::pow (10.0f, (gd[i] - 0.7f) / 20.0f);
        }
        static const int base[4] = { 1049, 1361, 1663, 2011 };
        const double T60 = 1.2;
        for (int i = 0; i < 4; ++i)
        {
            len[i] = (int) (base[i] * sr / 44100.0) | 1; line[i].assign ((size_t) len[i], 0.0f); pos[i] = 0; lp[i] = 0.0f;
            fb[i] = (float) std::pow (10.0, -3.0 * len[i] / (T60 * sr));
        }
    }
    // in: dry stereo; adds `mix` * wet to L/R in place
    void process (float* L, float* R, int n, float mix)
    {
        if (mix <= 0.0f || erBuf.empty()) return;
        for (int s = 0; s < n; ++s)
        {
            const float m = 0.5f * (L[s] + R[s]);
            erBuf[(size_t) erPos] = m;
            float eL = 0.0f, eR = 0.0f;
            for (int i = 0; i < kTaps; ++i)
            {
                eL += gl[i] * erBuf[(size_t) ((erPos - dl[i] + erLen) % erLen)];
                eR += gr[i] * erBuf[(size_t) ((erPos - dr[i] + erLen) % erLen)];
            }
            erPos = (erPos + 1) % erLen;
            float o[4], sum = 0.0f;
            for (int i = 0; i < 4; ++i) { o[i] = line[i][(size_t) pos[i]]; lp[i] = 0.7f * o[i] + 0.3f * lp[i]; sum += lp[i]; }
            for (int i = 0; i < 4; ++i)
            {
                const float f = fb[i] * (lp[i] - 0.5f * sum);
                line[i][(size_t) pos[i]] = 0.5f * m + f;
                if (++pos[i] >= len[i]) pos[i] = 0;
            }
            const float tL = 0.5f * (o[0] + o[1] - o[2] - o[3]), tR = 0.5f * (o[0] - o[1] + o[2] - o[3]);
            L[s] += mix * (eL + tL); R[s] += mix * (eR + tR);
        }
    }
private:
    static constexpr int kTaps = 6;
    std::vector<float> erBuf; int erLen = 0, erPos = 0; int dl[kTaps], dr[kTaps]; float gl[kTaps], gr[kTaps];
    std::vector<float> line[4]; int len[4], pos[4]; float fb[4], lp[4];
};

// ---------------------------------------------------------------------------
class DrumEngine
{
public:
    explicit DrumEngine (double sr = 44100.0) { setSampleRate (sr); }

    void setHammer (HammerType t) { hammer = t; }
    void setRoomMix (float m)     { roomMix = std::clamp (m, 0.0f, 0.5f); }
    void setDamping (float d)     { damping = std::clamp (d, 0.25f, 4.0f); }    // multiplies every decay rate
    void setStrikePos (float p)   { strikeOffset = (std::clamp (p, 0.0f, 1.0f) - 0.5f) * 0.6f; }  // 0.5 = neutral
    void setLimiter (bool on)     { limiterOn = on; }
    void seed (uint32_t s)        { noise.s = s ? s : 1u; }

    void setSampleRate (double sr)
    {
        sampleRate = sr; room.prepare (sr);
        for (int i = 0; i < kNumInstruments; ++i)
        {
            targetHz[i] = currentHz[i] = kVoicing[i].defaultHz;
            thetaI[i] = 2.0f * kPi * hash01 ((uint32_t) i, 9999u);
        }
    }

    const Recipe& getRecipe (int inst) const { return kVoicing[inst]; }
    void  setPitchHz (int inst, float hz) { const Recipe& r = kVoicing[inst]; targetHz[inst] = std::clamp (hz, r.minHz, r.maxHz); }
    float getPitchHz (int inst) const     { return currentHz[inst]; }

    void allNotesOff() { for (auto& bank : voices) for (auto& v : bank) v.active = false; }

    // ------------------------------------------------------------------ trigger
    void trigger (int inst, float velocity = 1.0f)
    {
        const Recipe& r = kVoicing[inst];
        const float sr = (float) sampleRate;

        if (r.chokeGroup != 0)
            for (int o = 0; o < kNumInstruments; ++o)
                if (o != inst && kVoicing[o].chokeGroup == r.chokeGroup)
                    for (auto& v : voices[o]) if (v.active && ! v.choking) chokeVoice (v);

        Voice* slot = nullptr; int oldest = -1;
        for (auto& v : voices[inst])
        {
            if (! v.active) { slot = &v; break; }
            if (v.n > oldest) { oldest = v.n; slot = &v; }
        }
        Voice& v = *slot;
        v.active = true; v.choking = false; v.n = 0; v.xprev = 0.0f; v.fade = 1.0f;
        v.nModes = 0; v.glideActive = false; v.nRes = 0; v.hasRattle = false; v.nl = r.nl;

        const float vel = std::clamp (velocity, 0.0f, 1.5f);
        const float hz = targetHz[inst];
        v.hzAtTrigger = hz;
        const float damp = r.dampScale * damping;

        // ---- hammer contact pulse (Hertz: force ~ sin^1.5, duration ~ v^-0.2)
        static const float tau0[3]  = { 0.00010f, 0.00020f, 0.0014f };   // s  (Hertz estimates, see Renders/RESEARCH.md)
        static const float hgain[3] = { 1.00f, 0.85f, 0.70f };
        static const float scr0[3]  = { 0.60f, 0.40f, 0.08f };
        const float tau = tau0[hammer] * r.tauScale * std::pow (std::max (vel, 0.05f), -0.2f) * (1.0f + 0.08f * noise.next());
        const float T = std::max (3.0f, tau * sr);
        const int   N = std::min ((int) std::ceil (T), kMaxPulse - 2);
        float area = 0.0f;
        for (int i = 0; i < N; ++i)
        {
            float s = ((float) i + 0.5f < T) ? std::sin (kPi * ((float) i + 0.5f) / T) : 0.0f;
            s = s * std::sqrt (s); v.pulse[i] = s; area += s;
        }
        const float pk = hgain[hammer] * vel / std::max (area, 1e-6f);
        for (int i = 0; i < N; ++i) v.pulse[i] *= pk;
        v.pulseLen = N;
        v.scrape = scr0[hammer] * r.scrape * (0.25f + 0.75f * std::min (vel, 1.0f));   // contact "tick" grows with impact speed

        // ---- strike point
        const float rr = std::clamp (r.strikeR + strikeOffset + r.strikeRJit * noise.next(), 0.02f, 0.98f);
        const float th0 = 2.0f * kPi * noise.uniform();
        const float thL = 0.6f, thR = -0.6f, thI = thetaI[inst];
        const float pos = rr * (float) (tables::kProfilePts - 1);
        const int   i0 = std::min ((int) pos, tables::kProfilePts - 2); const float fr = pos - (float) i0;

        v.panL = std::cos ((r.pan + 1.0f) * kPi * 0.25f); v.panR = std::sin ((r.pan + 1.0f) * kPi * 0.25f);

        float sig[kMaxModes];
        int   nm = 0; float fTop = 0.0f;
        const float nyq = 0.45f * sr;
        const float glideMaxHz = 1500.0f;
        const float outG = r.outGain;

        auto addMode = [&] (float f, float weight, float sigma, float pL, float pR, bool structural)
        {
            if (nm >= kMaxModes || f >= nyq || f < 15.0f) return;
            const float w = 2.0f * kPi * f / sr, rk = std::exp (-sigma / sr);
            v.a1[nm] = 2.0f * rk * std::cos (w); v.a2[nm] = -rk * rk; v.y1[nm] = v.y2[nm] = 0.0f;
            v.g[nm] = weight * outG; v.pl[nm] = pL * v.panL; v.pr[nm] = pR * v.panR;
            v.w0[nm] = w; v.gl[nm] = (structural && f < glideMaxHz) ? 1.0f : 0.0f;
            sig[nm] = sigma; if (structural) fTop = std::max (fTop, f);
            ++nm;
        };
        auto sigmaOf = [&] (float f) { return damp * (tables::kSigma0 + kPi * tables::kEta * f + tables::kSigma2 * f * f); };
        auto radiation = [&] (float ratio, int n)      // amplitude radiation efficiency of an (n)-order mode (baffled-piston low-ka law)
        {
            const float x = std::max (1e-3f, ratio * 0.5236f);   // kR, R scaled with the drum: depends only on ratio
            const float p = (float) (n + 1), xp = std::pow (x, p);
            return xp / std::sqrt (1.0f + xp * xp);
        };
        auto jit = [&] { return 1.0f + 0.115f * noise.next(); };             // +-1 dB per mode per hit
        auto fj  = [&] { return 1.0f + 0.001f * noise.next(); };             // +-0.1 % frequency jitter
        auto splitFrac = [&] { return 0.01f * r.splitPct * (0.6f + 0.8f * noise.uniform()); };

        // ---- struck plate
        const int sk = r.plateSkip;
        const float anchor = 1.0f + r.plateStretch * (tables::kPlate[sk].ratio - 1.0f);
        const bool  drumLike = (sk == 0);
        for (int k = sk, cnt = 0; k < tables::kNumPlateModes && cnt < r.plateModes; ++k, ++cnt)
        {
            const auto& m = tables::kPlate[k];
            const float ratio = 1.0f + r.plateStretch * (m.ratio - 1.0f);
            float f = hz * ratio / anchor;
            if (f >= nyq) break;
            const float W = m.prof[i0] + fr * (m.prof[i0 + 1] - m.prof[i0]);
            const float rad = drumLike ? radiation (ratio, m.n) : 1.0f;
            const float irr = 1.0f + (drumLike ? 0.003f : 0.008f) * (2.0f * hash01 ((uint32_t) inst, (uint32_t) k) - 1.0f);
            f *= irr;
            const float base = W * rad * r.plateAmp;
            if (m.n == 0) { addMode (f * fj(), base * jit(), sigmaOf (f), 1.0f, 1.0f, true); continue; }
            const float d = (float) m.n * (th0 - thI);
            const float dl = (float) m.n * (thL - thI), dr = (float) m.n * (thR - thI);
            if (cnt < r.pairModes)
            {
                const float dlt = splitFrac();
                addMode (f * (1.0f - 0.5f * dlt) * fj(), base * std::cos (d) * jit(), sigmaOf (f), std::cos (dl), std::cos (dr), true);
                addMode (f * (1.0f + 0.5f * dlt) * fj(), base * std::sin (d) * jit(), sigmaOf (f), std::sin (dl), std::sin (dr), true);
            }
            else
                addMode (f * fj(), base * std::cos (d) * jit(), sigmaOf (f), std::cos (dl), std::cos (dr), true);
        }
        // ---- side wall (Donnell shell)
        for (int k = 0; k < r.shellModes && k < tables::kNumShellModes; ++k)
        {
            const auto& m = tables::kShell[k];
            const float f = hz * m.ratio;
            if (f >= nyq) break;
            const float ax = std::sin ((float) m.m * kPi * r.shellXs);
            const float base = r.shellAmp * ax * radiation (m.ratio, m.n);
            if (m.n == 0) { addMode (f * fj(), base * jit(), sigmaOf (f), 1.0f, 1.0f, true); continue; }
            const float d = (float) m.n * (th0 - thI), dl = (float) m.n * (thL - thI), dr = (float) m.n * (thR - thI);
            const float dlt = splitFrac();
            addMode (f * (1.0f - 0.5f * dlt), base * std::cos (d) * jit(), sigmaOf (f), std::cos (dl), std::cos (dr), true);
            addMode (f * (1.0f + 0.5f * dlt), base * std::sin (d) * jit(), sigmaOf (f), std::sin (dl), std::sin (dr), true);
        }
        // ---- enclosed air (fixed T60; excited by lid volume motion)
        for (int k = 0; k < r.cavModes && k < tables::kNumCavityModes; ++k)
        {
            const auto& m = tables::kCavity[k];
            const float f = hz * m.ratio;
            if (f >= nyq) break;
            const float cpl = (m.n == 0) ? 1.0f : 0.7f * std::cos ((float) m.n * (th0 - thI));
            addMode (f, r.cavAmp * cpl * jit(), 6.9078f / std::max (r.cavT60, 0.02f), std::cos ((float) m.n * (thL - thI)), std::cos ((float) m.n * (thR - thI)), false);
        }
        v.nModes = nm;

        // ---- small amplitude-dependent glide (tension modulation), low modes only
        if (r.pitchEnvAmt > 0.0f && vel > 0.0f)
        {
            v.glideActive = true; v.glideDelta = r.pitchEnvAmt * std::min (vel, 1.0f); v.glideCount = 16;
            v.glideDecay = std::exp (-16.0f / (std::max (r.pitchEnvDecayMs, 1.0f) * 0.001f * sr));
            for (int k = 0; k < nm; ++k) applyGlide (v, k);
        }

        // ---- snare wires
        if (r.rattle > 0.0f)
        {
            v.hasRattle = true; v.rattleAmp = 0.35f * r.rattle; v.env = v.peak = 0.0f;
            static const float rf[3] = { 2600.0f, 4100.0f, 7300.0f };
            for (int j = 0; j < 3; ++j)
            {
                const float w = 2.0f * kPi * rf[j] / sr, rk = std::exp (-kPi * rf[j] / (40.0f * sr));
                v.ra1[j] = 2.0f * rk * std::cos (w); v.ra2[j] = -rk * rk; v.ry1[j] = v.ry2[j] = 0.0f;
            }
        }

        // ---- residual noise bands above the last modelled mode (statistically equals a dense mode set)
        if (r.residual > 0.0f && fTop > 0.0f && fTop < 0.40f * sr)
        {
            const float fLo = fTop * 1.05f, fHi = nyq;
            const float lo = fTop * 0.7f; float EL = 0.0f, ER = 0.0f;
            for (int k = 0; k < nm; ++k)
                if (v.gl[k] >= 0.0f && v.w0[k] * sr / (2.0f * kPi) >= lo)
                { const float e = v.g[k] * v.g[k] / (4.0f * sig[k]); EL += e * v.pl[k] * v.pl[k]; ER += e * v.pr[k] * v.pr[k]; }
            const float df = std::max (fTop - lo, 1.0f); EL *= sr / df; ER *= sr / df;   // sample-domain energy: sum y^2 = g^2 fs / (4 sigma)
            auto pulseMag = [&] (float f)
            {
                float re = 0.0f, im = 0.0f; const float w = 2.0f * kPi * f / sr;
                for (int i = 0; i < v.pulseLen; ++i) { re += v.pulse[i] * std::cos (w * (float) i); im -= v.pulse[i] * std::sin (w * (float) i); }
                return std::sqrt (re * re + im * im);
            };
            const float pTop = std::max (pulseMag (fTop), 1e-9f);
            const float rb = std::pow (fHi / fLo, 0.25f), q = 1.0f / (std::sqrt (rb) - 1.0f / std::sqrt (rb));
            v.nRes = kMaxResBands;
            for (int b = 0; b < kMaxResBands; ++b)
            {
                const float fc = fLo * std::pow (fHi / fLo, ((float) b + 0.5f) / (float) kMaxResBands);
                const float sb = sigmaOf (fc), pm = std::min (pulseMag (fc) / pTop, 1.5f);
                v.resL[b].setBandpass (fc, q, sr); v.resR[b].setBandpass (fc, q, sr);
                v.resAmpL[b] = r.residual * std::sqrt (sb * EL) * pm * 1.7321f;   // noise.next() is uniform[-1,1): std 1/sqrt(3) -> x sqrt(3) gives unit-variance input
                v.resAmpR[b] = r.residual * std::sqrt (sb * ER) * pm * 1.7321f;
                v.resDec[b]  = std::exp (-sb / sr);
            }
        }
    }

    // ------------------------------------------------------------------ process (stereo, ADDS into L/R)
    void process (float* outL, float* outR, int numSamples)
    {
        for (int pos = 0; pos < numSamples; pos += kChunk)
        {
            const int m = std::min (kChunk, numSamples - pos);
            const float coef = std::exp (-(float) m / (0.02f * (float) sampleRate));   // per-block smoothing (was per-call: a bug)
            for (int i = 0; i < kNumInstruments; ++i) currentHz[i] = targetHz[i] + coef * (currentHz[i] - targetHz[i]);

            float mixL[kChunk], mixR[kChunk];
            std::memset (mixL, 0, sizeof (float) * (size_t) m); std::memset (mixR, 0, sizeof (float) * (size_t) m);
            for (int inst = 0; inst < kNumInstruments; ++inst)
                for (auto& v : voices[inst])
                    if (v.active) renderVoice (v, kVoicing[inst], inst, m, mixL, mixR);

            room.process (mixL, mixR, m, roomMix);
            if (limiterOn) for (int i = 0; i < m; ++i) { mixL[i] = kCeil * std::tanh (mixL[i] / kCeil); mixR[i] = kCeil * std::tanh (mixR[i] / kCeil); }
            for (int i = 0; i < m; ++i) { outL[pos + i] += mixL[i]; outR[pos + i] += mixR[i]; }
        }
    }

    // mono convenience (legacy API): adds 0.5*(L+R)
    void process (float* out, int numSamples)
    {
        float l[kChunk], r[kChunk];
        for (int pos = 0; pos < numSamples; pos += kChunk)
        {
            const int m = std::min (kChunk, numSamples - pos);
            std::memset (l, 0, sizeof (float) * (size_t) m); std::memset (r, 0, sizeof (float) * (size_t) m);
            process (l, r, m);
            for (int i = 0; i < m; ++i) out[pos + i] += 0.5f * (l[i] + r[i]);
        }
    }

private:
    static constexpr float kCeil = 0.944f;       // -0.5 dBFS soft ceiling
    double sampleRate = 44100.0;
    Voice voices[kNumInstruments][kMaxInstances];
    float targetHz[kNumInstruments] = {}, currentHz[kNumInstruments] = {}, thetaI[kNumInstruments] = {};
    NoiseGen noise; Room room;
    HammerType hammer = WoodStick;
    float roomMix = 0.12f, damping = 1.0f, strikeOffset = 0.0f; bool limiterOn = true;

    static void applyGlide (Voice& v, int k)
    {
        if (v.gl[k] <= 0.0f) return;
        const float rk = std::sqrt (std::max (-v.a2[k], 0.0f));
        v.a1[k] = 2.0f * rk * std::cos (v.w0[k] * (1.0f + v.glideDelta));
    }

    void chokeVoice (Voice& v) const
    {
        const float rc = std::exp (-6.9078f / (0.015f * (float) sampleRate));        // 15 ms T60
        for (int k = 0; k < v.nModes; ++k)
        {
            const float rk = std::sqrt (std::max (-v.a2[k], 1e-12f)), cw = v.a1[k] / (2.0f * rk);
            v.a1[k] = 2.0f * rc * cw; v.a2[k] = -rc * rc;
        }
        for (int b = 0; b < v.nRes; ++b) v.resDec[b] = std::min (v.resDec[b], rc);
        v.choking = true; v.glideActive = false;
    }

    void renderVoice (Voice& v, const Recipe& r, int inst, int m, float* mixL, float* mixR)
    {
        (void) r;
#if OILDRUM_LEGACY_GLIDE
        if (std::fabs (currentHz[inst] - v.hzAtTrigger) > 1e-3f)
        {
            const float s = currentHz[inst] / v.hzAtTrigger;
            for (int k = 0; k < v.nModes; ++k)
            { const float rk = std::sqrt (std::max (-v.a2[k], 0.0f)); v.a1[k] = 2.0f * rk * std::cos (v.w0[k] * s); }
        }
#else
        (void) inst;
#endif
        int done = 0;
        while (done < m)
        {
            int seg = m - done;
            if (v.glideActive) seg = std::min (seg, v.glideCount);
            renderSegment (v, seg, mixL + done, mixR + done);
            done += seg;
            if (v.glideActive)
            {
                v.glideCount -= seg;
                if (v.glideCount <= 0)
                {
                    v.glideDelta *= v.glideDecay; v.glideCount = 16;
                    if (v.glideDelta < 1e-4f) { v.glideDelta = 0.0f; v.glideActive = false; }
                    for (int k = 0; k < v.nModes; ++k) applyGlide (v, k);
                }
            }
        }
        // prune inaudible modes; retire the voice when nothing is left
        if (v.n > v.pulseLen + 1)
            for (int k = 0; k < v.nModes;)
            {
                if (std::fabs (v.y1[k]) + std::fabs (v.y2[k]) < 3.0e-6f)
                {
                    const int l = --v.nModes;
                    v.a1[k] = v.a1[l]; v.a2[k] = v.a2[l]; v.y1[k] = v.y1[l]; v.y2[k] = v.y2[l]; v.g[k] = v.g[l];
                    v.pl[k] = v.pl[l]; v.pr[k] = v.pr[l]; v.w0[k] = v.w0[l]; v.gl[k] = v.gl[l];
                }
                else ++k;
            }
        bool resAlive = false;
        for (int b = 0; b < v.nRes; ++b) if (v.resAmpL[b] + v.resAmpR[b] > 1.0e-5f) resAlive = true;
        bool ratAlive = false;
        if (v.hasRattle) for (int j = 0; j < 3; ++j) if (std::fabs (v.ry1[j]) > 1.0e-6f) ratAlive = true;
        if ((v.nModes == 0 && ! resAlive && ! ratAlive && v.n > v.pulseLen + 1) || v.n > (int) (8.0 * sampleRate)) v.active = false;
    }

    void renderSegment (Voice& v, int seg, float* mixL, float* mixR)
    {
        const int nm = v.nModes;
        float* __restrict a1 = v.a1; float* __restrict a2 = v.a2; float* __restrict y1 = v.y1; float* __restrict y2 = v.y2;
        const float* g = v.g; const float* pl = v.pl; const float* pr = v.pr;
        for (int i = 0; i < seg; ++i)
        {
            const int idx = v.n + i;
            float sl = 0.0f, sr = 0.0f;
            if (idx <= v.pulseLen)
            {
                const float x = (idx < v.pulseLen) ? v.pulse[idx] * (1.0f + v.scrape * noise.next()) : 0.0f, xp = v.xprev;
                for (int k = 0; k < nm; ++k)
                {
                    const float y = a1[k] * y1[k] + a2[k] * y2[k] + g[k] * (x - 0.5f * a1[k] * xp);
                    y2[k] = y1[k]; y1[k] = y; sl += y * pl[k]; sr += y * pr[k];
                }
                v.xprev = x;
            }
            else
                for (int k = 0; k < nm; ++k)
                {
                    const float y = a1[k] * y1[k] + a2[k] * y2[k];
                    y2[k] = y1[k]; y1[k] = y; sl += y * pl[k]; sr += y * pr[k];
                }

            if (v.nl > 0.0f)      // memoryless "bloom": cubic + soft ceiling (~-0.9 dB at 0.4 FS), unity small-signal gain
            {
                float u = 2.0f * sl; u += v.nl * u * u * u; sl = 0.5f * std::tanh (0.7f * u) * (1.0f / 0.7f);
                u = 2.0f * sr;       u += v.nl * u * u * u; sr = 0.5f * std::tanh (0.7f * u) * (1.0f / 0.7f);
            }
            if (v.hasRattle)      // wires: micro-impacts driven by shell amplitude
            {
                const float mag = std::fabs (0.5f * (sl + sr));
                v.env = std::max (mag, v.env * 0.999f); v.peak = std::max (v.peak, v.env);
                float p = v.env / (v.peak + 1e-12f); p = std::max (0.0f, p - 0.04f) * 1.04f;
                float imp = 0.0f;
                if (noise.uniform() < p * 0.08f) imp = noise.next() * v.rattleAmp * v.peak * p;
                float ro = 0.0f;
                for (int j = 0; j < 3; ++j)
                {
                    const float y = v.ra1[j] * v.ry1[j] + v.ra2[j] * v.ry2[j] + imp;
                    v.ry2[j] = v.ry1[j]; v.ry1[j] = y; ro += y;
                }
                sl += ro * v.panL * 1.4142f; sr += ro * v.panR * 1.4142f;
            }
            if (v.nRes > 0)
            {
                for (int b = 0; b < v.nRes; ++b)
                {
                    sl += v.resAmpL[b] * v.resL[b].process (noise.next());
                    sr += v.resAmpR[b] * v.resR[b].process (noise.next());
                    v.resAmpL[b] *= v.resDec[b]; v.resAmpR[b] *= v.resDec[b];
                }
            }
            if (v.choking) { v.fade *= 0.996f; sl *= v.fade; sr *= v.fade; }
            mixL[i] += sl; mixR[i] += sr;
        }
        v.n += seg;
    }
};

} // namespace oildrum
