// Voicing.h -- GENERATED by Tools/modes.py from Tools/voicing.json. DO NOT EDIT BY HAND.
#pragma once
namespace oildrum {

// Per-instrument recipe. `defaultHz`/`minHz`/`maxHz` mirror the UI parameter ranges in PluginProcessor.cpp.
struct Recipe
{
    float defaultHz;
    float minHz;
    float maxHz;
    int plateModes;
    int plateSkip;
    float plateAmp;
    float plateStretch;
    int shellModes;
    float shellAmp;
    float shellXs;
    int cavModes;
    float cavAmp;
    float cavT60;
    float dampScale;
    float splitPct;
    int pairModes;
    float strikeR;
    float strikeRJit;
    float tauScale;
    float scrape;
    float pitchEnvAmt;
    float pitchEnvDecayMs;
    float rattle;
    float nl;
    float residual;
    float pan;
    int chokeGroup;
    float outGain;
};

inline constexpr int kNumInstruments = 15;

inline constexpr Recipe kVoicing[kNumInstruments] = {
  /* Bass Drum      */ { 55.0f, 30.0f, 120.0f, 70, 0, 1.0f, 0.8f, 12, 0.25f, 0.12f, 4, 0.5f, 0.5f, 4.0f, 0.15f, 24, 0.25f, 0.06f, 1.0f, 1.0f, 0.04f, 8.0f, 0.0f, 0.08f, 0.0f, 0.0f, 0, 0.044039f },
  /* Snare 1        */ { 190.0f, 100.0f, 400.0f, 80, 0, 1.0f, 0.7f, 24, 0.3f, 0.12f, 2, 0.15f, 0.15f, 2.5f, 0.3f, 32, 0.55f, 0.05f, 1.0f, 1.0f, 0.02f, 8.0f, 1.0f, 0.15f, 0.0f, -0.15f, 0, 0.027257f },
  /* Snare 2        */ { 160.0f, 90.0f, 350.0f, 80, 0, 1.0f, 0.7f, 24, 0.3f, 0.12f, 2, 0.15f, 0.15f, 2.0f, 0.45f, 32, 0.5f, 0.05f, 1.0f, 1.0f, 0.02f, 8.0f, 1.4f, 0.15f, 0.0f, 0.1f, 0, 0.017184f },
  /* Low Tom 1      */ { 95.0f, 47.5f, 209.0f, 64, 0, 1.0f, 0.8f, 20, 0.3f, 0.12f, 3, 0.35f, 0.35f, 1.7f, 0.2f, 32, 0.45f, 0.05f, 1.0f, 1.0f, 0.04f, 8.0f, 0.0f, 0.15f, 0.0f, 0.35f, 0, 0.048438f },
  /* Low Tom 2      */ { 105.0f, 52.5f, 231.0f, 64, 0, 1.0f, 0.8f, 20, 0.3f, 0.12f, 3, 0.35f, 0.35f, 1.9f, 0.3f, 32, 0.5f, 0.05f, 1.0f, 1.0f, 0.04f, 8.0f, 0.0f, 0.15f, 0.0f, 0.25f, 0, 0.049074f },
  /* Mid Tom 1      */ { 145.0f, 72.5f, 319.0f, 64, 0, 1.0f, 0.8f, 20, 0.3f, 0.12f, 3, 0.35f, 0.3f, 1.7f, 0.2f, 32, 0.45f, 0.05f, 1.0f, 1.0f, 0.04f, 8.0f, 0.0f, 0.15f, 0.0f, 0.1f, 0, 0.056545f },
  /* Mid Tom 2      */ { 160.0f, 80.0f, 352.0f, 64, 0, 1.0f, 0.8f, 20, 0.3f, 0.12f, 3, 0.35f, 0.3f, 1.9f, 0.3f, 32, 0.5f, 0.05f, 1.0f, 1.0f, 0.04f, 8.0f, 0.0f, 0.15f, 0.0f, -0.05f, 0, 0.063019f },
  /* High Tom 1     */ { 210.0f, 105.0f, 462.0f, 64, 0, 1.0f, 0.8f, 20, 0.3f, 0.12f, 3, 0.35f, 0.25f, 1.9f, 0.2f, 32, 0.45f, 0.05f, 1.0f, 1.0f, 0.04f, 8.0f, 0.0f, 0.15f, 0.0f, -0.2f, 0, 0.0709f },
  /* High Tom 2     */ { 230.0f, 115.0f, 506.0f, 64, 0, 1.0f, 0.8f, 20, 0.3f, 0.12f, 3, 0.35f, 0.25f, 2.1f, 0.3f, 32, 0.5f, 0.05f, 1.0f, 1.0f, 0.04f, 8.0f, 0.0f, 0.15f, 0.0f, -0.3f, 0, 0.070721f },
  /* Splash         */ { 500.0f, 250.0f, 1000.0f, 150, 14, 1.0f, 1.0f, 0, 0.3f, 0.12f, 0, 0.3f, 0.4f, 5.0f, 0.5f, 40, 0.85f, 0.05f, 1.0f, 1.5f, 0.0f, 8.0f, 0.0f, 0.12f, 0.7f, 0.45f, 0, 0.028489f },
  /* Ride           */ { 420.0f, 200.0f, 800.0f, 170, 14, 1.0f, 1.0f, 0, 0.3f, 0.12f, 0, 0.3f, 0.4f, 0.4f, 0.5f, 40, 0.7f, 0.06f, 1.0f, 1.2f, 0.0f, 8.0f, 0.0f, 0.12f, 0.7f, 0.55f, 0, 0.021256f },
  /* Hi-Hat Closed  */ { 500.0f, 250.0f, 900.0f, 140, 14, 1.0f, 1.0f, 0, 0.3f, 0.12f, 0, 0.3f, 0.4f, 9.0f, 0.5f, 30, 0.9f, 0.04f, 1.0f, 1.5f, 0.0f, 8.0f, 0.0f, 0.1f, 0.7f, -0.4f, 1, 0.02845f },
  /* Hi-Hat Open    */ { 500.0f, 250.0f, 900.0f, 140, 14, 1.0f, 1.0f, 0, 0.3f, 0.12f, 0, 0.3f, 0.4f, 1.3f, 0.5f, 30, 0.9f, 0.04f, 1.0f, 1.5f, 0.0f, 8.0f, 0.0f, 0.15f, 0.7f, -0.4f, 1, 0.019113f },
  /* Cowbell        */ { 560.0f, 300.0f, 1100.0f, 10, 0, 1.0f, 1.0f, 0, 0.3f, 0.12f, 0, 0.3f, 0.4f, 3.0f, 0.2f, 10, 0.6f, 0.05f, 1.0f, 1.0f, 0.0f, 8.0f, 0.0f, 0.1f, 0.0f, 0.2f, 0, 0.1246f },
  /* Rimshot        */ { 350.0f, 180.0f, 700.0f, 48, 0, 1.0f, 0.7f, 30, 0.6f, 0.04f, 0, 0.3f, 0.4f, 14.0f, 0.3f, 32, 0.85f, 0.03f, 0.7f, 2.5f, 0.0f, 8.0f, 0.0f, 0.15f, 0.5f, -0.1f, 0, 0.087917f },
};

inline const char* instrumentName (int i)
{
    static const char* names[kNumInstruments] = {
        "Bass Drum", "Snare 1", "Snare 2", "Low Tom 1", "Low Tom 2", "Mid Tom 1", "Mid Tom 2", "High Tom 1", "High Tom 2", "Splash", "Ride", "Hi-Hat Closed", "Hi-Hat Open", "Cowbell", "Rimshot"
    };
    return (i >= 0 && i < kNumInstruments) ? names[i] : "?";
}

} // namespace oildrum
